export const products = [
    {
      id: "421754",
      image: "Avatar1",
      Fname: "Ava Abad",
      PODNumber: "POD 1754",
      Semester: "Spring 2017",
      Date: "27-02-2022",
      DueDate: "27-03-2022",
      Time: "1:00 PM",
      School: "Crooks Elem",
      Subject: "English",
      Mentor: "Brooklyn Simmons",
      Phase: "Pre Teaching",
      Observation: "1",
      Mood: "-",
      LPlanStatus: "Inprogress",
      PreObsStatus: "Submitted",
      PostObsStatus: "Pending",
    },
    {
      id: "421755",
      image: "Avatar2",
      Fname: "Alan Donald",
      PODNumber: "POD 1754",
      Semester: "Spring 2017",
      Date: "27-02-2022",
      DueDate: "27-03-2022",
      Time: "1:00 PM",
      School: "Crooks Elem",
      Subject: "English",
      Mentor: "Brooklyn Simmons",
      Phase: "Pre Teaching",
      Observation: "1",
      Mood: "-",
      LPlanStatus: "Submitted",
      PreObsStatus: "Submitted",
      PostObsStatus: "Submitted",
    },
    {
      id: "421756",
      image: "Avatar3",
      Fname: "Ava Abad",
      PODNumber: "POD 1754",
      Semester: "Spring 2017",
      Date: "27-02-2022",
      DueDate: "27-03-2022",
      Time: "1:00 PM",
      School: "Crooks Elem",
      Subject: "English",
      Mentor: "Brooklyn Simmons",
      Phase: "Pre Teaching",
      Observation: "1",
      Mood: "-",
      LPlanStatus: "Inprogress",
      PreObsStatus: "Inprogress",
      PostObsStatus: "Pending",
    },
    {
      id: "421757",
      image: "Avatar4",
      Fname: "Ava Abad",
      PODNumber: "POD 1754",
      Semester: "Spring 2017",
      Date: "27-02-2022",
      DueDate: "27-03-2022",
      Time: "1:00 PM",
      School: "Crooks Elem",
      Subject: "English",
      Mentor: "Brooklyn Simmons",
      Phase: "Pre Teaching",
      Observation: "1",
      Mood: "-",
      LPlanStatus: "Submitted",
      PreObsStatus: "Pending",
      PostObsStatus: "Submitted",
    },

    {
      id: "421758",
      image: "Avatar2",
      Fname: "Ava Abad",
      PODNumber: "POD 1754",
      Semester: "Spring 2017",
      Date: "27-02-2022",
      DueDate: "27-03-2022",
      Time: "1:00 PM",
      School: "Crooks Elem",
      Subject: "English",
      Mentor: "Brooklyn Simmons",
      Phase: "Pre Teaching",
      Observation: "1",
      Mood: "-",
      LPlanStatus: "Inprogress",
      PreObsStatus: "Submitted",
      PostObsStatus: "Pending",
    },
    {
      id: "421759",
      image: "Avatar4",
      Fname: "Ava Abad",
      PODNumber: "POD 1754",
      Semester: "Spring 2017",
      Date: "27-02-2022",
      DueDate: "27-03-2022",
      Time: "1:00 PM",
      School: "Crooks Elem",
      Subject: "English",
      Mentor: "Brooklyn Simmons",
      Phase: "Pre Teaching",
      Observation: "1",
      Mood: "-",
      LPlanStatus: "Pending",
      PreObsStatus: "Inprogress",
      PostObsStatus: "Inprogress",
    },
    {
      id: "421760",
      image: "Avatar1",
      Fname: "Ava Abad",
      PODNumber: "POD 1754",
      Semester: "Spring 2017",
      Date: "27-02-2022",
      DueDate: "27-03-2022",
      Time: "1:00 PM",
      School: "Crooks Elem",
      Subject: "English",
      Mentor: "Brooklyn Simmons",
      Phase: "Pre Teaching",
      Observation: "1",
      Mood: "-",
      LPlanStatus: "Inprogress",
      PreObsStatus: "Submitted",
      PostObsStatus: "Pending",
    },
    {
      id: "421761",
      image: "Avatar1",
      Fname: "Ava Abad",
      PODNumber: "POD 1754",
      Semester: "Spring 2017",
      Date: "27-02-2022",
      DueDate: "27-03-2022",
      Time: "1:00 PM",
      School: "Crooks Elem",
      Subject: "English",
      Mentor: "Brooklyn Simmons",
      Phase: "Pre Teaching",
      Observation: "1",
      Mood: "-",
      LPlanStatus: "Submitted",
      PreObsStatus: "Submitted",
      PostObsStatus: "Submitted",
    },
    {
      id: "421762",
      image: "Avatar1",
      Fname: "Ava Abad",
      PODNumber: "POD 1754",
      Semester: "Spring 2017",
      Date: "27-02-2022",
      DueDate: "27-03-2022",
      Time: "1:00 PM",
      School: "Crooks Elem",
      Subject: "English",
      Mentor: "Brooklyn Simmons",
      Phase: "Pre Teaching",
      Observation: "1",
      Mood: "-",
      LPlanStatus: "Inprogress",
      PreObsStatus: "Submitted",
      PostObsStatus: "Pending",
    },
    {
      id: "421763",
      image: "Avatar1",
      Fname: "Ava Abad",
      PODNumber: "POD 1754",
      Semester: "Spring 2017",
      Date: "27-02-2022",
      DueDate: "27-03-2022",
      Time: "1:00 PM",
      School: "Crooks Elem",
      Subject: "English",
      Mentor: "Brooklyn Simmons",
      Phase: "Pre Teaching",
      Observation: "1",
      Mood: "-",
      LPlanStatus: "Submitted",
      PreObsStatus: "Submitted",
      PostObsStatus: "Submitted",
    },
    {
      id: "421764",
      image: "Avatar1",
      Fname: "Ava Abad",
      PODNumber: "POD 1754",
      Semester: "Spring 2017",
      Date: "27-02-2022",
      DueDate: "27-03-2022",
      Time: "1:00 PM",
      School: "Crooks Elem",
      Subject: "English",
      Mentor: "Brooklyn Simmons",
      Phase: "Pre Teaching",
      Observation: "1",
      Mood: "-",
      LPlanStatus: "Inprogress",
      PreObsStatus: "Submitted",
      PostObsStatus: "Pending",
    },
  ];